spring.application.name=BankSystem
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/medical_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=6`01o/]$p;6!(aBFd]M>:5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGeneration2025BankSystemSuperSecretKey1234567890
jwt.expiration=86400000